version: '3.7'

services:

  nginx:
    image: nginx:1.17.5
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /opt/www/moberries/static:/opt/www/static
      - /tmp/images:/opt/www/images
    depends_on:
      - moberries_pizza

  # django gunicorn
  moberries_pizza:
    build: .
    image: moberries_pizza:latest
    volumes:
#      - /opt/www/moberries/conf:/opt/www/conf
      - /opt/www/moberries/static:/opt/www/static
    command: gunicorn wsgi:application --bind 0.0.0.0:8000 -w 4
    restart: always
#    environment:
#      MBPIZZA_CONF: /opt/www/conf/django.yaml
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - /opt/www/moberries/postgres12.0:/var/lib/postgresql/data/
